name:                essentials-of-compilation

dependencies:
- base >= 4.7 && < 5
- array
- containers
- mtl
- parsec
- process 
- system-filepath
- random

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
- ScopedTypeVariables
- OverloadedStrings
- LambdaCase

library:
  source-dirs: src

tests:
  essentials-of-compilation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - essentials-of-compilation
    - directory
    - tasty
    - tasty-hunit
    - temporary
